{:externs ["browserific/cordova/externs/accelerometer.ext.js"
           "browserific/cordova/externs/battery.ext.js"
           "browserific/cordova/externs/browser.ext.js"
           "browserific/cordova/externs/camera.ext.js"
           "browserific/cordova/externs/capture.ext.js"
           "browserific/cordova/externs/compass.ext.js"
           "browserific/cordova/externs/connection.ext.js"
           "browserific/cordova/externs/contacts.ext.js"
           "browserific/cordova/externs/device.ext.js"
           "browserific/cordova/externs/dialogs.ext.js"
           "browserific/cordova/externs/file.ext.js"
           "browserific/cordova/externs/geolocation.ext.js"
           "browserific/cordova/externs/globalization.ext.js"
           "browserific/cordova/externs/media.ext.js"
           "browserific/cordova/externs/splashscreen.ext.js"
           "browserific/cordova/externs/statusbar.ext.js"
           "browserific/cordova/externs/transfer.ext.js"
           "browserific/cordova/externs/vibration.ext.js"]}
