(ns leiningen.browserific
  (:require [leiningen.browserific.config :as c]
            [leiningen.help :as lhelp]
            [leiningen.core.main :as lmain]))

(defn- once
  "Compile browserific files once and quit"
  []
  (c/build-config))

(defn- auto
  "Automatically recompile browserific files when they are changed"
  [])

(defn- clean
  "Remove files previously generated by browserific"
  [])

(defn- sample
  "Show a sample config.edn"
  [])

(defn- config
  "Launch a server over port 4242 that has a GUI for building a config.edn file"
  [])

;; FIXME: Should we use yet another build map in project.clj? Can this be avoided?
;; TODO: add more specific browser/mobile commands like test, package, etc.
(defn browserific
  "Run lein-browserific"
  {:help-arglists '([once auto clean sample config])
   :subtasks [#'once #'auto #'clean #'sample #'config]}
  ([project]
     (println
      (lhelp/help-for "browserific"))
     (lmain/abort))
  ([project subtask]
     (case subtask
       "once" (once)
       "auto" (println "auto not done")
       "clean" (println "clean not done")
       "sample" (println "sample not done")
       (do
          (println
            "ERROR: Subtask " (str subtask ) " not found."
            (lhelp/subtask-help-for *ns* #'browserific))
          (lmain/abort)))))
